# Generated by Django 5.2.3 on 2025-07-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='trainer',
        ),
        migrations.AddField(
            model_name='client',
            name='trainers',
            field=models.ManyToManyField(related_name='clients', to='base.trainerprofile'),
        ),
    ]
