# Generated by Django 5.2.3 on 2025-07-08 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_client_remove_invoice_company_invoice_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='invoice',
        ),
        migrations.AddField(
            model_name='session',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='invoice.client'),
        ),
    ]
