# Generated by Django 5.2.3 on 2025-07-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_remove_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='sessions',
            field=models.ManyToManyField(blank=True, related_name='invoices', to='invoice.session'),
        ),
    ]
