# Generated by Django 5.2.3 on 2025-07-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0012_invoice_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='account_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='account_owner',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='bank_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='email',
            field=models.EmailField(default='email@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='postal_code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='role',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sort_code',
            field=models.CharField(default='', max_length=6),
        ),
    ]
