# Generated by Django 5.2.3 on 2025-07-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0016_alter_class_date_alter_class_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='number_of_students',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
