# Generated by Django 5.2.3 on 2025-07-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0017_class_number_of_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='maximum_students',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
