# Generated by Django 5.2.3 on 2025-07-13 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0018_class_maximum_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='maximum_students',
            new_name='maximum_participants',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='number_of_students',
            new_name='participants',
        ),
    ]
