# Generated by Django 5.2.3 on 2025-07-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0019_rename_maximum_students_class_maximum_participants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='maximum_participants',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
