# Generated by Django 5.2.3 on 2025-07-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0021_remove_session_date_remove_session_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_length',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
