# Generated by Django 5.2.3 on 2025-07-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0022_alter_session_amount_alter_session_session_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('invoiced', 'Invoiced')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
