# Generated by Django 5.2.3 on 2025-07-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0023_session_status_alter_invoice_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='account_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='account_owner',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='email',
            field=models.EmailField(blank=True, default='email@example.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sort_code',
            field=models.CharField(blank=True, default='', max_length=6, null=True),
        ),
    ]
